before_deploy:
- openssl aes-256-cbc -K $encrypted_6d2e60986cdb_key -iv $encrypted_6d2e60986cdb_iv
  -in .copr.enc -out .copr -d
deploy:
  skip_cleanup: true
  provider: script
  script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest
    /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --nowait
    simc/stable fedora/SPECS/wreport.spec"
  true:
    branch: master
    condition: $DOCKER_IMAGE = centos:8 && $TRAVIS_CPU_ARCH != ppc64le # Diabling deploy for ppc64le
dist: bionic
arch:
- amd64
- ppc64le
env:
- DOCKER_IMAGE=centos:7
- DOCKER_IMAGE=centos:8
- DOCKER_IMAGE=fedora:31
- DOCKER_IMAGE=fedora:32
- DOCKER_IMAGE=fedora:33
- DOCKER_IMAGE=fedora:rawhide
language: generic
matrix:
  allow_failures:
  - env: DOCKER_IMAGE=fedora:rawhide
  exclude:
  - arch: ppc64le
    env: DOCKER_IMAGE=fedora:rawhide  # ppc doesn't have this image
script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash
  .travis-build.sh $DOCKER_IMAGE
services:
- docker
sudo: required
